# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Device-Arduino-LCD
version:      1.02
version_from: lib/Device/Arduino/LCD.pm
installdirs:  site
requires:
    Class::MethodMaker:            0
    Device::SerialPort:            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
